name: README build
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 4 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.head_commit.author.name != 'llotze/GitHub-Actions-Bot'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated from v2
        with:
          fetch-depth: 1
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Get Python 3.11 
        uses: actions/setup-python@v5  # Updated from v2
        with:
          python-version: '3.11'
      - name: Configure pip cache
        uses: actions/cache@v4  # Updated from v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/cache/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Install dependencies
        run: python -m pip install -r cache/requirements.txt
      - name: Update README file
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: python today.py
      - name: Commit
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |-
          git add .
          git config --global user.email "github-actions-bot@llotze.github.io"
          git config --global user.name "llotze/GitHub-Actions-Bot"
          git commit -m "Updated README" -a || echo "No changes to commit"
          git push
